version: 0.0
os: linux

files:
  - source: /
    destination: /home/spoteditor/Spoteditor-Backend
    file_exists_behavior: OVERWRITE

permissions:
  - object: /
    mode: 755     # 권한
    owner: spoteditor
    group: spoteditor

hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 180
      runas: spoteditor

  BeforeInstall:  # 설치전 디렉토리 클린
    - location: scripts/directory_clean.sh
      runas: spoteditor
